name: Build Nuru-Lsp Executable

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name}}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            name: "Ubuntu",
            os: ubuntu-latest,
          }
          - {
            name: "Windows",
            os: windows-latest,
          }
          - {
            name: "MacOs",
            os: macos-latest,
          }
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Run Tests
        run: go mod tidy && go test ./tests/ 

      - name: Build ${{matrix.config.name}}
        run: go mod tidy && go build 

      - name: Zip Unix
        if: matrix.config.os != 'windows-latest'
        run: |
          zip -r ./nuru-lsp-${{matrix.config.os}}.zip ./nuru-lsp

      - name: Zip Windows
        if: matrix.config.os == 'windows-latest'
        run: |
          tar -cf ./nuru-lsp-${{matrix.config.os}}.zip nuru-lsp.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: contains(github.ref, 'tags/v')
        with:
          files: ./nuru-lsp-${{matrix.config.os}}.zip
    
